import icono_3 from '../img/icono-3.webp';
import icono_2 from '../img/icono-2.webp';
import icono_4 from '../img/icono-4.webp';
import icono_6 from '../img/icono-6.webp';
import netflix_img from '../img/netflix-img.webp';

const products = {
  play_3:[
    {
      id: 1,
      img: icono_3,
      megas: 50,
      full: 75,
      promo: 50,
      promoTime: "3 Meses",
      price: 77.50,
      regularPrice: 155,
    },
    {
      id: 2,
      img: icono_3,
      megas: 80,
      full: 120,
      promo: 50,
      promoTime: "3 Meses",
      price: 82.50,
      regularPrice: 165,
    },
    {
      id: 3,
      img: icono_3,
      megas: 150,
      full: 200,
      promo: 50,
      promoTime: "3 Meses",
      price: 90,
      regularPrice: 180,
    },
    {
      id: 4,
      img: icono_3,
      megas: 200,
      full: 300,
      promo: 50,
      promoTime: "3 Meses",
      price: 95,
      regularPrice: 190,
    },
    {
      id: 5,
      img: icono_3,
      megas: 250,
      full: 300,
      promo: 50,
      promoTime: "3 Meses",
      price: 102.50,
      regularPrice: 205,
    },
    {
      id: 6,
      img: icono_3,
      megas: 300,
      full: 400,
      promo: 50,
      promoTime: "3 Meses",
      price: 140,
      regularPrice: 280,
    },
    {
      id: 7,
      img: icono_3,
      megas: 500,
      full: 600,
      promo: 50,
      promoTime: "3 Meses",
      price: 160,
      regularPrice: 320,
    },
    {
      id: 8,
      img: icono_3,
      megas: 1000,
      full: null,
      promo: 50,
      promoTime: "3 Meses",
      price: 260,
      regularPrice: 520,
    },
  ],
  play_2_tv:[
    {
      id: 1,
      img: icono_2,
      megas: 50,
      full: 75,
      promo: 50,
      promoTime: "3 Meses",
      price: 72.50,
      regularPrice: 145,
    },
    {
      id: 2,
      img: icono_2,
      megas: 80,
      full: 120,
      promo: 50,
      promoTime: "3 Meses",
      price: 77.50,
      regularPrice: 155,
    },
    {
      id: 3,
      img: icono_2,
      megas: 150,
      full: 200,
      promo: 50,
      promoTime: "3 Meses",
      price: 85,
      regularPrice: 170,
    },
    {
      id: 4,
      img: icono_2,
      megas: 200,
      full: 300,
      promo: 50,
      promoTime: "3 Meses",
      price: 92.50,
      regularPrice: 185,
    },
    {
      id: 5,
      img: icono_2,
      megas: 250,
      full: 300,
      promo: 50,
      promoTime: "3 Meses",
      price: 100,
      regularPrice: 200,
    },
    {
      id: 6,
      img: icono_2,
      megas: 300,
      full: 400,
      promo: 50,
      promoTime: "3 Meses",
      price: 137.50,
      regularPrice: 275,
    },
    {
      id: 7,
      img: icono_2,
      megas: 500,
      full: 600,
      promo: 50,
      promoTime: "3 Meses",
      price: 157.50,
      regularPrice: 315,
    },
    {
      id: 8,
      img: icono_2,
      megas: 1000,
      full: null,
      promo: 50,
      promoTime: "3 Meses",
      price: 257.50,
      regularPrice: 515,
    },
  ],
  play_2_phone:[
    {
      id: 1,
      img: icono_4,
      megas: 50,
      full: 75,
      promo: 50,
      promoTime: "1 Mes",
      price: 40,
      regularPrice: 80,
    },
    {
      id: 2,
      img: icono_4,
      megas: 80,
      full: 120,
      promo: 50,
      promoTime: "1 Mes",
      price: 45,
      regularPrice: 90,
    },
    {
      id: 3,
      img: icono_4,
      megas: 150,
      full: 200,
      promo: 50,
      promoTime: "1 Mes",
      price: 52.50,
      regularPrice: 105,
    },
    {
      id: 4,
      img: icono_4,
      megas: 200,
      full: 300,
      promo: 50,
      promoTime: "1 Mes",
      price: 60,
      regularPrice: 120,
    },
    {
      id: 5,
      img: icono_4,
      megas: 250,
      full: 300,
      promo: 50,
      promoTime: "1 Mes",
      price: 67.50,
      regularPrice: 135,
    },
    {
      id: 6,
      img: icono_4,
      megas: 300,
      full: 400,
      promo: 50,
      promoTime: "1 Mes",
      price: 105,
      regularPrice: 210,
    },
    {
      id: 7,
      img: icono_4,
      megas: 500,
      full: 600,
      promo: 50,
      promoTime: "1 Mes",
      price: 125,
      regularPrice: 250,
    },
    {
      id: 8,
      img: icono_4,
      megas: 1000,
      full: null,
      promo: 50,
      promoTime: "1 Mes",
      price: 225,
      regularPrice: 450,
    },
  ],
  netflix:[
    {
      id: 1,
      img: icono_2,
      netflix: netflix_img,
      name: "2 play",
      megas: 60,
      full: 75,
      price: 110,
    },
    {
      id: 2,
      img: icono_2,
      netflix: netflix_img,
      name: "2 play",
      megas: 120,
      full: 150,
      price: 130,
    },
    {
      id: 3,
      img: icono_3,
      netflix: netflix_img,
      name: "3 play",
      megas: 120,
      full: 150,
      price: 210,
    },
    {
      id: 4,
      img: icono_3,
      netflix: netflix_img,
      name: "3 play",
      megas: 240,
      full: 300,
      price: 255,
    },
  ],
  internet:[
    {
      id: 1,
      img: icono_6,
      gigas: 100,
      megas: 10,
      price: 85,
      priceRouter: 359,
      model: "Huawei B612",
    }
  ]
};

export default products;